In [3]:
#1
#Write a NumPy program to test whether any of the elements of a given array is non-zero

import numpy as np

arr=np.array([[1,2,3,4],[2,2,3,5]])

found =False
for i in np.nditer(arr):
    if i == 0:
        found =True

if(found==True):
    print("yes")
else:
    print("no")
    

no


In [4]:
#2
#Write a NumPy program to test a given array element-wise for finiteness
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))


Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


In [5]:
#3
#Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array memory occupied by the arr

import numpy as np
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes


In [8]:
#4
#Write a NumPy program to create a 3x3 identity matrix
arr=np.identity(3,dtype="i")
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
#5
#Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution
rand=np.random.normal(0,1,15)
print(rand)

[ 0.07576612 -0.00338941 -0.21279406 -0.09846137 -0.69513422  1.51370736
  0.72248351 -0.31473058 -1.19300271 -1.35594567  1.021824   -0.34303136
 -0.08664747  1.27437522  1.00618774]


In [11]:
#6
#. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
arr=np.array(range(15,56),dtype="i")
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54], dtype=int32)

In [15]:
#7
import numpy as np
#Write a NumPy program to create a 3X4 array using and iterate over it
arr=np.array(range(0,12),dtype="i")
ar=arr.reshape(3,4)
print(ar)
for i in np.nditer(ar):
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
#8
#Write a NumPy program to create a vector of length 10 with values ​​evenly distributed between 5 and 50.
v=np.linspace(10,49,5)
v

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

In [25]:
#9
#Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
#arr=np.arange(21)
arr=np.array(range(0,21),dtype="i")
arr[14]=100
arr[(arr>=9) & (arr<=15)]*=-1
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, 100, -15,  16,  17,  18,  19,  20], dtype=int32)

In [26]:
#10
#rite a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
arr=np.random.randint(0,11,5)
arr


array([1, 1, 4, 8, 9])

In [28]:
#11
# Write a NumPy program to create a null vector of size 10 and update sixth value to 11
arr=np.zeros(10)
arr[5]=11
arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [31]:
#12
#Write a NumPy program to create a 2d array with 1 on the border and 0 inside
a=np.ones((5,5))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
#13
#Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern
a=np.zeros((8,8))
a[:,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [37]:
#14
#Write a NumPy program to create an empty and a full array.

f=np.empty((3,4))

y=np.full((3,3),6)
print(f)
print(y)

[[1.00383098e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [7.56587583e-307 2.75218430e+180 2.35783938e+184 1.20183186e-075]
 [8.82783567e+169 1.22523577e-046 7.61075959e-042 9.59373587e-071]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [43]:
#15
#Write a NumPy program to test whether each element of a 1-D array is also present in a second array
a=np.array([1,2,3,4])
b=np.array([1,2,3,6])
np.in1d(a,b)

#for i in a:
 #   if b[]

array([ True,  True,  True, False])

In [44]:
#16
#Write a NumPy program to get the unique elements of an array

a=np.array([1,2,3,4,5,1,2,3])
x=np.unique(a)
x

array([1, 2, 3, 4, 5])

In [45]:
#17
#difference

a=np.arange(4)
b=np.arange(4)
x=np.subtract(a,b)
x

array([0, 0, 0, 0])

In [46]:
#18
#Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.
a=np.arange(10)
b=np.arange(4)
x=np.union1d(a,b)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
#19
#Write a NumPy program to test whether any array element along a given axis evaluates to True.
#Note: 0 evaluates to False in python.

print(np.any([1,1,1,0]))
print(np.any([0,0,0]))

True
False


In [51]:
#20
#Write a NumPy program to repeat elements of an array.
ar=np.array([1,2,3,4],dtype="i")
x=np.repeat(ar,3)
x

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int32)

In [52]:
#21
#Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.
ar=np.arange(20)
x=ar[ar>10]
x

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
#22
#Write a NumPy program to compute the multiplication of two given matrixes
a=[[1,2],[3,4]]
b=[[1,2],[3,4]]

x=np.product
print(x)

[[ 7 10]
 [15 22]]


In [54]:
#23
#Write a NumPy program to compute the outer product of two given matrixes

import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result = np.outer(p, q)
print("Outer product of the said two vectors:")
print(result)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [55]:
#24
##Write a NumPy program to compute the cross product of two given matrixes

import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q):")
print(result1)
print("cross product of the said two vectors(q, p):")
print(result2)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
cross product of the said two vectors(p, q):
[ 2 -3]
cross product of the said two vectors(q, p):
[-2  3]


In [56]:
#25
#Write a NumPy program to create a new array of 3*5, filled with 2

ar=np.full((3,5),2)
ar

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [57]:
#26
#Write a NumPy program to create a new shape to an array without changing its data. Go to the editor

ar=[[1,2],[3,4],[5,6]]
x=np.reshape(ar,(2,3))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
#27
# Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50

a=np.arange(51)
b=np.array(range(10,51),dtype="i")

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [59]:
#28
# Write a NumPy program to collapse a 3-D array into one dimension array.

arr=np.arange(9)
arr=np.reshape(arr,(3,3))
print(arr)
arr=np.reshape(arr,-1)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [61]:
#29
#write a NumPy program to move the specified axis backwards, until it lies in a given position

arr=np.ones((1,2,3,4))
print(np.rollaxis(arr,3,1).shape)

(1, 4, 2, 3)


In [70]:
#30
#Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis.
import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))


Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [71]:
#31
#Write a NumPy program to generate five random numbers from the normal distribution.

arr=np.random.normal(size=5)
arr

array([-1.75910306, -1.59569494, -1.85827978,  1.06897917, -0.64656355])

In [83]:
#32
#. Write a NumPy program to generate six random integers between 10 and 30. Go to the editor

arr=np.random.rand(3,3,3)
arr

array([[[0.99530526, 0.39959944, 0.84563896],
        [0.16966647, 0.64009955, 0.1810365 ],
        [0.67354745, 0.54316848, 0.15398902]],

       [[0.87334689, 0.05963598, 0.31102601],
        [0.11670427, 0.11147699, 0.37686094],
        [0.04472371, 0.22145462, 0.08869204]],

       [[0.68008023, 0.25238907, 0.34273995],
        [0.72015745, 0.25337629, 0.13214847],
        [0.95525245, 0.35781285, 0.02555956]]])

In [90]:
#33
#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

arr=np.random.rand(5,5,5)
print(arr)
print(arr.max())
print(arr.max())


[[[0.9012879  0.41705122 0.33458662 0.33275575 0.58290835]
  [0.66214487 0.55218165 0.33439507 0.4200178  0.58087449]
  [0.69964938 0.99807986 0.17258565 0.53574633 0.35195823]
  [0.20535191 0.4962716  0.79920174 0.73394278 0.17749688]
  [0.29707674 0.6372668  0.39912514 0.06623466 0.80073698]]

 [[0.38309501 0.57793015 0.78213464 0.09475964 0.03480797]
  [0.16529331 0.9731419  0.39323468 0.96308512 0.35326443]
  [0.08752411 0.0071442  0.68828126 0.49018015 0.63474642]
  [0.91425867 0.47553408 0.96474098 0.90492993 0.43830949]
  [0.35419467 0.12043002 0.51387013 0.49071836 0.72259044]]

 [[0.1623054  0.30767029 0.19550239 0.89048477 0.5987594 ]
  [0.38047108 0.52227159 0.31413214 0.25635002 0.45470164]
  [0.92565    0.18650297 0.93804173 0.16931874 0.60148191]
  [0.89135983 0.66357203 0.49799293 0.39157182 0.18998163]
  [0.91478743 0.60272051 0.04692418 0.52305723 0.93829733]]

 [[0.75577559 0.13272669 0.89284435 0.96730028 0.02603899]
  [0.78086109 0.21732362 0.79481583 0.91205745 0.9

In [96]:
#34
# Write a NumPy program to shuffle numbers between 0 and 10 (inclusive
a=np.array(range(0,10),dtype="i")

x=np.random.permutation(a)
print(x)


[5 4 0 9 2 3 6 1 8 7]


In [101]:
#35
#Write a NumPy program to create a random vector of size 10 and sort it
a=np.random.random(10)
print(a)
sorted(a)

[0.0421019  0.2388386  0.37022314 0.44858252 0.16787455 0.8857052
 0.18461724 0.99586244 0.95832453 0.62926181]


[0.04210189659476593,
 0.16787455490998848,
 0.18461724188966877,
 0.2388386001648346,
 0.37022313994660316,
 0.44858251911521596,
 0.6292618068596303,
 0.8857052039733124,
 0.958324531839224,
 0.9958624392480012]

In [106]:
#36
#Write a NumPy program to find the nearest value from a given value in an array
x=np.random.uniform(1,12,10)
print(x)
v=4
result=x.flat[np.abs(x-v).argmin()]
result

[10.48916161  5.46285052  1.65292743  4.77069135  1.82676341  5.90363494
  3.92586026  4.4448476   5.46026679  9.90634873]


3.9258602606222794

In [120]:
#37
#Write a NumPy program to check two random arrays are equal or not

a=np.random.randint(0,2,4)
b=np.random.randint(0,2,4)

r=np.allclose(a,b)
r


False

In [123]:
#38
#Write a NumPy program to create random vector of size 15 and replace the maximum value by -1
arr=np.random.random(15)
arr[arr==arr.max()]=-1
arr

array([ 0.55004991,  0.013185  ,  0.63972733,  0.20471316,  0.66599236,
        0.05031982,  0.49728186,  0.12446068,  0.35097545, -1.        ,
        0.06951142,  0.03094424,  0.00466368,  0.04987032,  0.72827279])

In [130]:
#39
#Write a NumPy program to find the most frequent value in an array

arr=np.random.randint(0,30,30)
print(arr)
print(np.bincount(arr).argmax())
print(np.bincount(arr))


[28 17  1  0 26  2 10 17  9 29  5 21 12  7 10  4 26  9  3 23 26 22 12 16
 20  5 29  8  0 13]
26
[2 1 1 1 1 2 0 1 1 2 2 0 2 1 0 0 1 2 0 0 1 1 1 1 0 0 3 0 1 2]


In [133]:
#40
#Write a NumPy program to get the n largest values of an array

x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [139]:
#41
#Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array
ar=np.array([[4,1],[3,2]],dtype="i")
x=np.sort(ar,axis=1)
print(x)
y=np.sort(ar,axis=0)
print(y)

[[1 4]
 [2 3]]
[[3 1]
 [4 2]]


In [145]:
#42
#Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on heigh
data_type = [('name', 'S15'), ('class', int), ('height', float)]
sudents_details = [('Paul', 5, 48.5), ('Nail', 6, 52.5),('James', 5, 42.10), ('Pit', 5, 40.11)]



s=np.array(sudents_details,dtype=data_type)
re=np.sort(s,order='height')
re

array([(b'Pit', 5, 40.11), (b'James', 5, 42.1 ), (b'Paul', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

In [147]:
#43
# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal
data_type = [('name', 'S15'), ('class', int), ('height', float)]
sudents_details = [('Paul', 5, 48.5), ('Nail', 6, 52.5),('James', 5, 42.10), ('Pit', 5, 40.11)]


s=np.array(sudents_details,dtype=data_type)
re=np.sort(s,order=['class','height'])
re

array([(b'Pit', 5, 40.11), (b'James', 5, 42.1 ), (b'Paul', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])

In [150]:
#44
#Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])

ind=np.lexsort((student_id,student_height))
print(ind)

for n in ind:
    print(student_id[n], student_height[n])

[4 0 5 3 6 1 2]
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [151]:
#45
#Write a NumPy program to get the indices of the sorted elements of a given array

import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


In [152]:
#46
#Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).

import numpy as np
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 4))

Original array:
[ 70  50  20  30 -11  60  50  40]

After partitioning on 4 the position:
[-11  30  20  40  50  50  60  70]


In [153]:
#47
#. Write a NumPy program to sort the specified number of elements from beginning of a given array

arr=np.random.random(7)
re=arr[np.argpartition(arr,range(5))]
re

array([0.13679861, 0.19064495, 0.30320112, 0.46233576, 0.80699726,
       0.9597011 , 0.94679873])

In [154]:
#48
#Write a NumPy program to sort an given array by the nth column

import numpy as np
print("Original array:\n")
nums = np.random.randint(0,10,(3,3))
print(nums)
print("\nSort the said array by the nth column: ")
print(nums[nums[:,1].argsort()])

Original array:

[[4 2 5]
 [4 7 0]
 [8 8 7]]

Sort the said array by the nth column: 
[[4 2 5]
 [4 7 0]
 [8 8 7]]


In [ ]:
#49
#